[package]
name = "teleport"
authors = ["github.com/Sealmex"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.81"
clap = { version = "3.2.6", features = ["derive"] }